Added Documentation
samdroid-apps/python-munsell pull request #1
Opened 2018-02-13 13:04 UTC by cogmind

Hi Sam,

Nice dictionary you've got there! I added some text to the Readme describing the different variables. I hope I got it right.

Best,
Daniel

2018-02-13 20:10 UTC, samdroid-apps requested changes
Thanks for writing this documentation - It would just be great if you could move it around a bit.

Once that is fixed, it will be good to merge.

2018-02-13 20:10 UTC, samdroid-apps commented on README.md
> +## Dictionary Structure ##
I'm not 100% sure; but I would prefer if this was inline in the `table.py` file; so that it is more obvious what the relevant dictionary is.

2018-02-13 20:10 UTC, samdroid-apps commented on README.md
> +## Munsell Hue Notation ##
This section is great

2018-02-13 20:10 UTC, samdroid-apps commented on README.md
> +## Dictionary Structure ##
When you move it there, maybe just put a paragraph in the README saying "there are docstrings in the __init__.py file (providing an abstraction for dealing with munesll colors) and table.py file (providing raw data about munsell colors"

2018-02-14 09:41 UTC, cogmind commented
I have made some changes in response to your review. And oops, I completely overlooked the init file, because I am not used to package level definitions. Looks good!

2018-02-14 20:10 UTC, merged

2018-02-14 20:10 UTC, samdroid-apps commented
Thanks for that @cogmind!